name: ArtemisX
url: https://github.com/wwwuxt/hexo-theme-artemisX

menu:
  首页: /
  归档: /archives
  标签: /tags
  关于: /about
  # 分类: /categories

GitHub: https://github.com/wwwuxt
RSS: /atom.xml

favicon: /favicon.ico
logo: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics: UA-108353521-1
google_adsense: 
baidu_autopush: true


# Copyright Infomation
copyright:
  since: 2017
  name: wwwuxt
  url: http://wwwuxt.cc

# github & coding pages deploy, get header to change copyright
double_deploy: true
deploy_server: 
